# Generated by Django 5.2.5 on 2025-08-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('details', models.TextField(verbose_name='تفاصيل المشروع')),
                ('total_target', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستهدف')),
                ('start_time', models.DateField(verbose_name='تاريخ بدء الحملة')),
                ('end_time', models.DateField(verbose_name='تاريخ انتهاء الحملة')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='project_pics/', verbose_name='الصورة الرئيسية')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ التبرع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التبرع')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL, verbose_name='المتبرع')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='projects.project', verbose_name='المشروع')),
            ],
        ),
    ]
