# Generated by Django 5.2.5 on 2025-08-10 17:22

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Donation Amount'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Donation Date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL, verbose_name='Donator'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(max_length=11, validators=[projects.models.validate_egyptian_phone_number], verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(verbose_name='Project Details'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(verbose_name='Campaign End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='project_pics/', verbose_name='Main Picture'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateField(verbose_name='Campaign Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Target'),
        ),
    ]
